public enum Orientation
{
    UP_ORIENTATION,
    UPRIGHT_ORIENTATION,
    RIGHT_ORIENTATION,
    DOWNRIGHT_ORIENTATION,
    DOWN_ORIENTATION,
    DOWNLEFT_ORIENTATION,
    LEFT_ORIENTATION,
    UPLEFT_ORIENTATION
}